spring:
  application:
    name: forge

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 2

      # Prevent premature disconnection
      # 29 minutes (just under typical 30 min DB timeout)
      max-lifetime: 1740000

      # 10 minutes idle allowed
      idle-timeout: 600000

      # 5 minutes, sends keep-alive pings
      keep-alive-time: 300000

      # 30s to wait for a new connection
      connection-timeout: 30000

      # Database connection validation
      validation-timeout: 5000
      validation-query: SELECT 1

    logging:
      level:
        org.springframework.boot.autoconfigure.jdbc: DEBUG
        com.zaxxer.hikari: DEBUG
  jpa:
    hibernate:
      ddl-auto: ${POSTGRES_DDL_SETTING}
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:

aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_BUCKET_NAME}
    bucket-url: ${AWS_BUCKET_URL}

forge:
  app:
    clerk:
      jwksUrl: ${CLERK_JWKS_URL}
      expectedIssuer: ${CLERK_EXPECTED_ISSUER}
      apiUrl: ${CLERK_API_URL}
      apiKey: ${CLERK_API_KEY}
    jwtSecret: ${JWT_SECRET}
    jwtExpireMs: ${JWT_EXPIRATION_MS}
    jwtRefreshExpireMs: ${JWT_REFRESH_EXPIRATION_MS}
    noImage: none
    cors: ${CORS_LINK}
    redis:
      uri: ${REDIS_CONNECTION}
    nextJs:
      apiKey: ${NEXTJS_SECRET_KEY}
