name: CI/CD for Spring Boot with Maven

env:
  MONGO_DATABASE: ${{secrets.MONGO_DATABASE}}
  MONGO_USER: ${{secrets.MONGO_USER}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
  MONGO_CLUSTER: ${{secrets.MONGO_CLUSTER}}
  AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
  AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
  AWS_REGION: ${{secrets.AWS_REGION}}
  AWS_BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}
  AWS_BUCKET_URL: ${{secrets.AWS_BUCKET_URL}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  JWT_EXPIRATION_MS: ${{secrets.JWT_EXPIRATION_MS}}
  JWT_REFRESH_EXPIRATION_MS: ${{secrets.JWT_REFRESH_EXPIRATION_MS}}
  CORS_LINK: ${{secrets.CORS_LINK}}

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: debian-12
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adoptopenjdk'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package -U

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packaged-application
        path: target/*.jar

  deploy:
    needs: build
    runs-on: debian-12

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: packaged-application
        path: "./artifact"

    - name: Verify artifact files
      run: ls -l ./artifact/*.jar

    - name: Setup key
      id: setup-key
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        echo "$DEPLOY_KEY" > $HOME/key.pem
        chmod 400 $HOME/key.pem

    - name: List contents of deployment directory
      run: ls -l "/home/admin/deployment"

    - name: Copy Files to Server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: admin
        key: ${{ secrets.DEPLOY_KEY }}
        port: 22
        source: "./artifact/*.jar"
        target: "/home/admin/deployment/"
        debug: true

    - name: Connect SSH and Restart Services
      run: |
        ssh -o StrictHostKeyChecking=no -o BatchMode=yes -i $HOME/key.pem admin@${{ secrets.DEPLOY_HOST }} << EOF
          sudo systemctl restart flavorforge
          sudo systemctl restart nginx
        EOF
