name: CI/CD for Spring Boot with Maven

env:
  MONGO_DATABASE: ${{secrets.MONGO_DATABASE}}
  MONGO_USER: ${{secrets.MONGO_USER}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
  MONGO_CLUSTER: ${{secrets.MONGO_CLUSTER}}
  AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
  AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
  AWS_REGION: ${{secrets.AWS_REGION}}
  AWS_BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}
  AWS_BUCKET_URL: ${{secrets.AWS_BUCKET_URL}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  JWT_EXPIRATION_MS: ${{secrets.JWT_EXPIRATION_MS}}
  JWT_REFRESH_EXPIRATION_MS: ${{secrets.JWT_REFRESH_EXPIRATION_MS}}
  CORS_LINK: ${{secrets.CORS_LINK}}

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packaged-application
        path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: packaged-application
        path: target/

    - name: Setup key
      id: setup-key
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        echo "$DEPLOY_KEY" >> $HOME/key.pem
        chmod 400 $HOME/key.pem

    - name: Copy JAR to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ubuntu
        key: ${{ secrets.DEPLOY_KEY }}
        source: "target/*.jar"
        target: "/home/ubuntu/deployment/"

    - name: Connect SSH and Restart Services
      run: |
        ssh -o StrictHostKeyChecking=no -i $HOME/key.pem admin@ec2-44-243-221-37.us-west-2.compute.amazonaws.com '
          sudo systemctl restart flavorforge &&
          sudo systemctl restart nginx
        '
